# Generated by Django 4.2.2 on 2023-07-08 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofiles',
            name='avatar',
            field=models.ImageField(default='images/avatar/HITESH.png', upload_to='images/avatar/'),
        ),
    ]
