# Generated by Django 4.2.2 on 2023-07-08 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_userprofiles_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='aparment',
            field=models.CharField(default='H.No.', max_length=220, null=True),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='street',
            field=models.CharField(default='Street/Landmark', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='userprofiles',
            name='avatar',
            field=models.ImageField(default='images/avatar/avtar.jpg', upload_to='images/avatar/'),
        ),
        migrations.AlterField(
            model_name='userprofiles',
            name='bio',
            field=models.CharField(default='Intraduce your self......', max_length=220, null=True),
        ),
    ]
